project:
  type: website

website:
  title: "Pablo Wolter"
  description: "A place for my ideas, work and dreams. Maybe"
  navbar:
    right:
      - text: Blog
      - href: blog.qmd
      - icon: github
        text: Github
        href: https://github.com/pwolter
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/pwolter/
format:
  html:
    theme: flatly

execute:
  freeze: auto
  
filters:
  - code-filename

